name: Release

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     node-version: [14.x]

    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          # node-version: ${{ matrix.node-version }}
          node-version: 16.x
          # cache: 'npm'
      - run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - run: npm ci
      - run: npm run test
      - run: npm run build
      - run: npm pack
      - run: npm run docs
      - name: Deploy Docs
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages-docs # The branch the action should deploy to.
          folder: ./typedoc # The folder the action should deploy.
      - run: npm run release
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          # access: public
          # check-version: false
